name: Sync with upstream

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16:00 (北京时间凌晨 0:00) 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取所有历史，以便能够推送
        
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/usebruno/bruno.git
        
    - name: Fetch upstream
      run: |
        git fetch upstream
        
    - name: Merge upstream
      run: |
        git checkout main
        git merge upstream/main --no-edit
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
